version: "3.8"

services:
  nuxt-app:
    build: .
    container_name: nuxt3-app
    ports:
      - "5000:5000" # Пробрасываем порт 5000
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0 # Важно для доступа внутри контейнера
      - NITRO_PORT=5000
    restart: unless-stopped
