services:
  frontend:
    build: ./client
    container_name: nuxt3-frontend
    expose:
      - "5000"
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=5000
    restart: unless-stopped

  backend:
    build: ./server
    container_name: fastapi-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: >-
      certonly --webroot --webroot-path=/var/www/certbot
      --email nikita.shutnikov@gmail.com --agree-tos --no-eff-email
      -d xn--80acj1aaqbbwm7a3h.xn--p1ai
      -d api.xn--80acj1aaqbbwm7a3h.xn--p1ai


volumes:
  pgdata: