"""Add unique name column

Revision ID: 2d308130b7ca
Revises: b45a09c6fbce
Create Date: 2025-01-26 22:24:46.322101

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d308130b7ca"
down_revision: Union[str, None] = "b45a09c6fbce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "attributes", ["name"])
    op.create_unique_constraint(None, "brands", ["name"])
    op.create_unique_constraint(None, "products", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_constraint(None, "brands", type_="unique")
    op.drop_constraint(None, "attributes", type_="unique")
    # ### end Alembic commands ###
