"""logo url add to service

Revision ID: 921b182d233c
Revises: 63f1fc202d1d
Create Date: 2025-03-28 18:14:35.843861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921b182d233c'
down_revision: Union[str, None] = '63f1fc202d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('services', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'description')
    op.drop_column('services', 'logo_url')
    # ### end Alembic commands ###
