"""utc-5

Revision ID: 5ad48f52e6a6
Revises: 0264a8a07ff2
Create Date: 2025-03-29 00:57:45.950192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ad48f52e6a6'
down_revision: Union[str, None] = '0264a8a07ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('attributes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('order_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('order_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('product_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('product_attributes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('product_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC-5', now())"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('product_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('product_attributes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('product_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('order_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('order_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('attributes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    op.alter_column('attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('UTC+5'::text, now())"),
               existing_nullable=False)
    # ### end Alembic commands ###
