"""photo url to product

Revision ID: 31324f3a4bc4
Revises: 921b182d233c
Create Date: 2025-03-28 20:36:57.509944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31324f3a4bc4'
down_revision: Union[str, None] = '921b182d233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_url', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo_url')
    # ### end Alembic commands ###
