"""many to many order services

Revision ID: a47e2885224a
Revises: 30ed85ff82a6
Create Date: 2025-03-18 16:23:21.992266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47e2885224a'
down_revision: Union[str, None] = '30ed85ff82a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type')
    )
    op.add_column('order_services', sa.Column('service_id', sa.UUID(), nullable=False))
    op.add_column('order_services', sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('order_services', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'order_services', 'services', ['service_id'], ['id'])
    op.drop_column('order_services', 'service_type')
    op.drop_column('order_services', 'price')
    op.add_column('products', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.add_column('order_services', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('order_services', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_services', type_='foreignkey')
    op.alter_column('order_services', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('order_services', 'custom_price')
    op.drop_column('order_services', 'service_id')
    op.drop_table('services')
    # ### end Alembic commands ###
