services:
  db:
    image: postgres:15
    container_name: prod_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conditioner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: prod_redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      args:
        ENV: "production"
    container_name: prod_fastapi_app
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    environment:
      - postgres_host=db
      - redis_host=redis
    ports:
      - "3000:3000"

volumes:
  postgres_data:
