services:
  db:
    container_name: conditioner
    image: postgres:17.2-alpine3.20

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:${POSTGRES_PORT}'
    restart: always

    volumes:
      - ./data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
volumes:
  data: