services:
  db:
    image: postgres:17.2-alpine3.20
    container_name: prod_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conditioner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
      args:
        ENV: "production"
    container_name: prod_fastapi_app
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - postgres_host=db
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
